### PR TITLE
Fix crash on exit plug after removing a user

### LINKED ISSUE #155: Segfault after deleting user and going back to main view
## Steps to Reproduce

1. Delete a user
2. Go back to the main Switchboard view by clicking the "All Settings" button
3. Observe crash

## Platform Information
6.0 Odin - current daily or compiled from git

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96328638-segfault-after-deleting-user-and-going-back-to-main-view?utm_campaign=plugin&utm_content=tracker%2F60744320&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60744320&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by vjr**
Fixes #155 

It appears the `UserItem` is not released even though it is being removed from its container here: https://github.com/elementary/switchboard-plug-useraccounts/blob/d60310f36e25f68344dca4e59172d78a8dc8b3b0/src/Widgets/UserListBox.vala#L94

And the accounts service seems to be sending user-changed signals *after* deleting the user which trigger the unreleased `UserItem` object.

### CODE REVIEW

**Comment by meisenzahl** [comment]
I can confirm that this works 🎉

@davidmhewitt what are your thoughts implementation wise?

**Comment by davidmhewitt** [comment]
I don't really like the idea that something is holding a reference to the `UserItem` that's preventing it from being destroyed when it's removed from the container.

@vjr Did you look into what that might be?

**Comment by vjr** [comment]
No, I only read the code and couldn't figure out what is preventing the useritem from being released. 

I'll once again try to identify the root cause, maybe try running valgrind and see if I can find something.

**Comment by davidmhewitt** [comment]
Looking at the code, it could be the avatar, because of `set_image_load_func`.

**Comment by vjr** [comment]
Okay, I'll look into it.

**Comment by vjr** [comment]
Nah, I couldn't track down the root cause, sorry. I have no idea if it's a bug in handy avatar or accounts service or somewhere else.

**Comment by vjr** [comment]
I might have been mistaken about `UserItem` not being released.

If I run switchboard in the terminal with debug messages enabled, it appears `accountsservice` is sending a `changed` signal from a deleted `user` but only if you add a user and then immediately remove it before exiting the plug.

I also noticed the user property `locked` is not toggling the `reveal-child` property of the lock symbol and the user avatar has the lock symbol visible when you create the user, but not if you later re-open the plug.

**Comment by vjr** [comment]
Just wanted to mention while I was trying a few things, the `UserItem` `lock-revealer` `reveal-child` property is not being toggled when you toggle the `Act.User` `locked` property by clicking the enable/disable button, but it does get set if I add a `lock_revealer.reveal_child = user.locked;` line inside the `user.changed.connect` signal handler in `UserItem.vala`

**Comment by jeremypw** [comment]
From my investigations, the non-destruction of UserItems is caused by `avatar`.  Removing this both stops the crash and causes the UserItems to destruct properly.  Will investigate further.

**Comment by jeremypw** [comment]
The cause is the signal handler connecting `user` and `avatar` if this is disconnected before removing from the user list then the UserItem destructs and the crash does not occur.

**Comment by jeremypw** [comment]
This problem be solved by making a *weak* signal handler connection but this not very elegant in Vala.  See https://stackoverflow.com/questions/39034280/vala-disconnecting-signal-handler-via-handler-id-from-class-destructor-fails

Tbh this solution is a much easier way of fixing the crash but UserItems are not destroyed.  I'll push a PR which does both for consideration.

**Comment by vjr** [comment]
Good stuff @jeremypw so closing this one.

**Pull request closed without merging**
